version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
        - '*'
  - package-ecosystem: "npm"
    directory: "/site/"
    versioning-strategy: increase
    schedule:
      interval: "weekly"
    groups:
      npm:
        patterns:
        - '*'
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "numpy"
    groups:
      pip:
        patterns:
        - '*'
