version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
        - '*'
  - package-ecosystem: "npm"
    directory: "/site/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "video.js"
        update-types: ["version-update:semver-major"]
    groups:
      npm:
        patterns:
        - '*'
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "numpy"
    groups:
      pip:
        patterns:
        - '*'
