version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
        - '*'
  - package-ecosystem: "npm"
    directory: "/site/"
    schedule:
      interval: "daily"
    groups:
      npm:
        patterns:
        - '*'
    ignore:
      - dependency-name: "eslint"
        versions: '>8'
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
