name: Publish on GitHub pages

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 7 * * */2'

permissions:
  packages: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)

      - name: Install dependencies
        run: sudo apt-get install -y mediainfo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt

      - name: Generate required dependencies
        run: |
          ./scripts/setup.sh

      - name: Provide url artifact
        uses: actions/upload-artifact@v3
        with:
          name: urls.json
          path: site/src/assets/json/urls.json

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version-file: '.nvmrc'

      - name: Install Node dependencies
        working-directory: ./site
        run: |
          yarn install

      - name: Lint and Validate JSON
        working-directory: ./site
        run: |
          yarn run eslint

      - name: Build site
        working-directory: ./site
        run: |
          yarn run vite build

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/dist
          force_orphan: true
