name: Publish on GitHub pages

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 7 * * */2'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:

      - name: Free some disk space
        run: |
          sudo rm -rf /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL

      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate required dependencies
        run: |
          ./scripts/setup.sh

      - name: Provide url artifact
        uses: actions/upload-artifact@v3
        with:
          name: urls.json
          path: site/src/assets/json/urls.json

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version-file: '.nvmrc'

      - name: Install Node dependencies
        working-directory: ./site
        run: |
          yarn install

      - name: Lint and Validate JSON
        working-directory: ./site
        run: |
          yarn run eslint

      - name: Build site
        working-directory: ./site
        run: |
          yarn run vite build

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/dist
          force_orphan: true
