name: Publish on GitHub pages

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
#  schedule:
#    - cron:  '0 7 * * 1'

permissions:
  packages: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)

      - name: Install dependencies
        run: sudo apt-get install -y mediainfo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt

      - name: Generate required dependencies
        run: |
          ./scripts/setup.sh

      - name: Provide url artifact
        uses: actions/upload-artifact@v4
        with:
          name: urls.json
          path: site/src/assets/json/urls.json

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version-file: '.nvmrc'

      - name: Install Node dependencies
        working-directory: ./site
        run: |
          npm i

      - name: Lint and Validate JSON
        working-directory: ./site
        run: |
          npx eslint

      - name: Build site
        working-directory: ./site
        run: |
          npx vite build

      - name: Copy generated files
        run: |
          cp ./site/src/assets/json/urls.json ./site/dist
          cp ./site/src/assets/json/pages.json ./site/dist

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/dist
          force_orphan: true
